SCREEN_SIZE = (600, 800)
GAME_NAME = "CarDriver251"
ICON_WAY = 'Assets\\ico.png'
ENEMY_IMAGES_DIR = 'Assets\\enemy'
PLAYER_SKINS_DIR = 'Assets\\playerSkins'
INTERFACE_IMAGES_DIR = 'Assets\\interface'
PLAYER_CONFIG_DIR = 'player.json'


MAIN_MENU_STATE = 0
GAME_STATE = 1
GARAGE_STATE = 2
SCORES_STATE = 3
GAME_OVER_STATE = 4
QUIT_STATE = 5
INTERFACE_STATE = [MAIN_MENU_STATE,]
